### ISSUE TITLE
不开源吗

### ISSUE THREAD

**Issue by yaoh3i** [boy-hack/go-strip#1]
老哥，不打算开源吗

**Comment by boy-hack** [comment]
看 https://mp.weixin.qq.com/s?__biz=MzU2NzcwNTY3Mg==&mid=2247484130&idx=1&sn=d482026bcd9d74b4b5bb5a62f02af10e&chksm=fc986bc5cbefe2d3e74ac3e892c10e9c65f968ac32bfbd3b0f373e09fe65c39f58ea3e62107f&token=1662333611&lang=zh_CN#rd

用gore改改就可以实现了

**Comment by novvoo** [comment]
使用pestudio分析还是有一条本地信息没混淆
更直接还是使用dockerfile去编译，生产环境也都是这么做的。

**Comment by 0x2E** [comment]
> 使用pestudio分析还是有一条本地信息没混淆
> 更直接还是使用dockerfile去编译，生产环境也都是这么做的。

@jingslunt 混淆的主要意义在于让程序在 IDA 下变得难以理解，提高逆向的难度，而不是防止泄露本地路径之类的信息
