### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by M09Ic** [boy-hack/go-strip#4]
## 报错信息:

❯ go-strip.exe -f .\hack-browser-data-v0.3.6-windows-32bit.exe -a -output hbd.exe

                       _        _
                      | |      (_)
  __ _  ___ ______ ___| |_ _ __ _ _ __
 / _  |/ _ \______/ __| __| '__| | '_ \
| (_| | (_) |     \__ \ |_| |  | | |_) |
\__, |\___/      |___/\__|_|  |_| .__/
__/ |                          | |
|___/                           |_|

2021/11/22 17:01:03 开始混淆
2021/11/22 17:01:03 文件结构:PE
2021/11/22 17:01:03 混淆 BuildId
2021/11/22 17:01:03 Compiler version: go1.16.2 (2021-03-11T17:08:05Z)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0xc6d77e]

goroutine 1 [running]:
github.com/goretk/gore/gosym.(*Table).GetGo12(...)
        /home/runner/work/go-strip-source/go-strip-source/gosym/symtab.go:485
github.com/goretk/gore.(*GoFile).GetGoRoot(0xc00009c000, 0x1a, 0xc000071f48)
        /home/runner/work/go-strip-source/go-strip-source/file.go:195 +0x3e
main.main()
        /home/runner/work/go-strip-source/go-strip-source/testM/main.go:48 +0x2d0

混淆linux版本的时候正常,windows版本报错

**Comment by boy-hack** [comment]
上传一下你的样本

**Comment by M09Ic** [comment]
导致报错的样本：

https://github.com/moonD4rk/HackBrowserData/releases/download/v0.3.6/hack-browser-data-v0.3.6-windows-64bit.zip

不过已经解决了，用linux环境交叉编译了一个exe，就可以正常混淆了，疑似使用了win32api的问题

**Comment by boy-hack** [comment]
新的更新修复了这个
