### ISSUE TITLE
windows下可以正常编译动态库和混淆，linux可以正常编译动态库但无法混淆

### ISSUE THREAD

**Issue by echo5188** [boy-hack/go-strip#5]
go版本1.16.1
**我的代码**
_main.go_
package main
import "C"
import "fmt"
//export Hello
func Hello(){
 fmt.Println(":hello")
}
func main(){}
**编译命令**
go build -buildmode=c-shared -x -v -o test.so -ldflags "-s -w" main.go
**混淆命令**
./go-strip -f test.so -a -output test.strip.so
**混淆开始**
_ _
| | ()
__ _ ___ ______ | | _ __ _ _ __
/ _ |/ _ ____/ _| | '| | '
| (| | () | _ \ || | | | |) |
_, |_/ |/_|| || ._/
/ | | |
|/ ||

2021/11/18 01:39:00 开始混淆
2021/11/18 01:39:00 文件结构:ELF
2021/11/18 01:39:00 混淆 BuildId
Error when extracting compiler information: no goversion found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x50c13b]

goroutine 1 [running]:
github.com/goretk/gore/gosym.(*Table).GetGo12(...)
/home/runner/work/go-strip-source/go-strip-source/gosym/symtab.go:485
github.com/goretk/gore.(*GoFile).GetGoRoot(0xc000060ea0, 0xc00000e018, 0xc000093f28)
/home/runner/work/go-strip-source/go-strip-source/file.go:195 +0x3b
main.main()
/home/runner/work/go-strip-source/go-strip-source/testM/main.go:48 +0x2c5
**我需要你的帮助**

**Comment by boy-hack** [comment]
上传一下你的样本

**Comment by echo5188** [comment]
> 上传一下你的样本
我的代码
main.go
package main
import "C"
import "fmt"
//export Hello
func Hello(){
 fmt.Println(":hello")
}
func main(){}
编译命令
go build -buildmode=c-shared -x -v -o test.so -ldflags "-s -w" main.go
混淆命令
./go-strip -f test.so -a -output test.strip.so

一个简单的cgo程序

**Comment by echo5188** [comment]
> 上传一下你的样本
这个是在linux环境下编译的混淆前文件
https://github.com/FlyFishTeam/strip/blob/main/test.so

**Comment by boy-hack** [comment]
看了下，不支持c-shared的混淆
